name: Bug report
description: Create a report to help us improve
labels: ["bug"]
assignees:
  - ClementGre
body:
  - type: checkboxes
    id: alreadyRequested
    attributes:
      label: Code of Conduct
      options:
        - label: I checked the bug was not already reported [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.3.1%22+-label%3A%22user+Issue%22+-label%3Aduplicate+-label%3Adocumentation+-label%3Aenhancement+-label%3A%22good+first+issue%22+-label%3A%22help+wanted%22+-label%3Aquestion)
        - label: I checked the bug is not an existing user issue [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+label%3A%22user+issue%22+)
          required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what the bug is.
  - type: textarea
    id: solutionLiked
    attributes:
      label: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
  - type: textarea
    id: alternative
    attributes:
      label: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additionalContext
    attributes:
      label: Additional context
      placeholder: Add any other context or screenshots about the feature request here.
